{
 "bad":{
  "exception":"HTTP Error 404: Not Found",
  "traceback":"Traceback (most recent call last):\n  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 578, in main\n    hash_type=attrs.get('hash_type', 'sha256'))\n  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 96, in run\n    migrate_return = migrator.migrate(recipe_dir, attrs, **kwargs)\n  File \"/root/repo/cf-scripts/conda_forge_tick/migrators.xsh\", line 334, in migrate\n    new_patterns = self.get_hash_patterns('meta.yaml', urls, hash_type)\n  File \"/root/repo/cf-scripts/conda_forge_tick/migrators.xsh\", line 264, in get_hash_patterns\n    hash = hash_url(url, hash_type)\n  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/rever/tools.xsh\", line 207, in hash_url\n    for b in stream_url_progress(url, verb='Hashing', quiet=quiet):\n  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/rever/tools.xsh\", line 179, in stream_url_progress\n    with urllib.request.urlopen(url) as f:\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 563, in error\n    result = self._call_chain(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 755, in http_error_302\n    return self.parent.open(new, timeout=req.timeout)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 563, in error\n    result = self._call_chain(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 755, in http_error_302\n    return self.parent.open(new, timeout=req.timeout)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 641, in http_response\n    'http', request, response, code, msg, hdrs)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 569, in error\n    return self._call_chain(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n  File \"/opt/conda/envs/run_env/lib/python3.7/urllib/request.py\", line 649, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\nurllib.error.HTTPError: HTTP Error 404: Not Found\n"
 },
 "conda-forge.yml":{},
 "feedstock_name":"l18n",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "home":"https://bitbucket.org/tkhyn/l18n",
   "license":"MIT",
   "license_family":"MIT",
   "license_file":"LICENSE.txt",
   "summary":"Internationalization for pytz timezones and territories"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"python -m pip install . --no-deps --ignore-installed"
  },
  "extra":{
   "recipe-maintainers":[
    "ocefpaf",
    "ocefpaf",
    "ocefpaf"
   ]
  },
  "package":{
   "name":"l18n",
   "version":"2016.6.4"
  },
  "requirements":{
   "host":[
    "python",
    "pip",
    "pytz >=2016.6",
    "six",
    "python",
    "pip",
    "pytz >=2016.6",
    "six",
    "python",
    "pip",
    "pytz >=2016.6",
    "six"
   ],
   "run":[
    "python",
    "pytz >=2016.6",
    "six",
    "python",
    "pytz >=2016.6",
    "six",
    "python",
    "pytz >=2016.6",
    "six"
   ]
  },
  "source":{
   "sha256":"a72b9a80b297da5bc807f347bfa61aa9900c35bf1bb55e61a17ec7e58d9e0de7",
   "url":"https://pypi.io/packages/source/l/l18n/l18n-2016.6.4.zip"
  },
  "test":{
   "imports":[
    "l18n",
    "l18n",
    "l18n"
   ]
  }
 },
 "name":"l18n",
 "new_version":"2018.5",
 "raw_meta_yaml":"{% set version = \"2016.6.4\" %}\n\npackage:\n  name: l18n\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/l/l18n/l18n-{{ version }}.zip\n  sha256: a72b9a80b297da5bc807f347bfa61aa9900c35bf1bb55e61a17ec7e58d9e0de7\n\nbuild:\n  number: 0\n  noarch: python\n  script: python -m pip install . --no-deps --ignore-installed\n\nrequirements:\n  host:\n    - python\n    - pip\n    - pytz >=2016.6\n    - six\n  run:\n    - python\n    - pytz >=2016.6\n    - six\n\ntest:\n  imports:\n    - l18n\n\nabout:\n  home: https://bitbucket.org/tkhyn/l18n\n  license: MIT\n  license_family: MIT\n  license_file: LICENSE.txt\n  summary: Internationalization for pytz timezones and territories\n\nextra:\n  recipe-maintainers:\n    - ocefpaf\n",
 "req":{
  "__set__":true,
  "elements":[
   "pip",
   "python",
   "pytz",
   "six"
  ]
 },
 "time":1568072508.9721167,
 "url":"https://pypi.io/packages/source/l/l18n/l18n-2016.6.4.zip",
 "version":"2016.6.4"
}