{
 "PRed":[
  {
   "PR":{
    "__lazy_json__":"pr_json/204225120.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Compiler",
    "migrator_version":0
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/243012790.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"CompilerRebuild",
    "migrator_version":1,
    "name":"Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/294669932.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.5.3"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/312949634.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.5.4"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/339860901.json"
   },
   "data":{
    "bot_rerun":true,
    "migrator_name":"MigrationYaml",
    "migrator_object_version":1,
    "migrator_version":0,
    "name":"python38"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/339934845.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"MigrationYaml",
    "migrator_object_version":1,
    "migrator_version":0,
    "name":"python38"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/352508177.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.5.7"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/360981267.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.5.6"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/383937090.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"2.6"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad":{
  "exception":"<class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
  "traceback":[
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 426, in _make_request",
   "    six.raise_from(e, None)",
   "  File \"<string>\", line 3, in raise_from",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 421, in _make_request",
   "    httplib_response = conn.getresponse()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 1344, in getresponse",
   "    response.begin()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 306, in begin",
   "    version, status, reason = self._read_status()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/http/client.py\", line 267, in _read_status",
   "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/socket.py\", line 589, in readinto",
   "    return self._sock.recv_into(b)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py\", line 326, in recv_into",
   "    raise timeout(\"The read operation timed out\")",
   "socket.timeout: The read operation timed out",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send",
   "    timeout=timeout",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 725, in urlopen",
   "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/util/retry.py\", line 403, in increment",
   "    raise six.reraise(type(error), error, _stacktrace)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/packages/six.py\", line 735, in reraise",
   "    raise value",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 677, in urlopen",
   "    chunked=chunked,",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 428, in _make_request",
   "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 336, in _raise_timeout",
   "    self, url, \"Read timed out. (read timeout=%s)\" % timeout_value",
   "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 196, in _request",
   "    return request_method(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 578, in post",
   "    return self.request('POST', url, data=data, json=json, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/session.py\", line 169, in request",
   "    response = super(GitHubSession, self).request(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 530, in request",
   "    resp = self.send(prep, **send_kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/sessions.py\", line 643, in send",
   "    r = adapter.send(request, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/requests/adapters.py\", line 529, in send",
   "    raise ReadTimeout(e, request=request)",
   "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 798, in main",
   "    hash_type=attrs.get(\"hash_type\", \"sha256\"),",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 243, in run",
   "    branch=branch_name,",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/git_utils.py\", line 285, in push_repo",
   "    pr = repo.create_pull(title, \"master\", head, body=body)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/decorators.py\", line 31, in auth_wrapper",
   "    return func(self, *args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/repos/repo.py\", line 1117, in create_pull",
   "    return self._create_pull(data)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/repos/repo.py\", line 120, in _create_pull",
   "    json = self._json(self._post(url, data=data), 201)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 221, in _post",
   "    return self._request(\"post\", url, data, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/github3/models.py\", line 201, in _request",
   "    raise exceptions.ConnectionError(exc)",
   "github3.exceptions.ConnectionError: <class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   ""
  ]
 },
 "conda-forge.yml":{
  "provider":{
   "win":"azure"
  }
 },
 "feedstock_name":"pyfmi",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "home":"http://www.jmodelica.org/",
   "license":"LGPL",
   "license_file":"LICENSE",
   "summary":"PyFMI is a package for loading and interacting with Functional Mock-Up Units"
  },
  "build":{
   "number":"0"
  },
  "extra":{
   "recipe-maintainers":[
    "jschueller",
    "chria",
    "jschueller",
    "chria",
    "jschueller",
    "chria"
   ]
  },
  "package":{
   "name":"pyfmi",
   "version":"2.6"
  },
  "requirements":{
   "build":[
    "c_compiler_stub",
    "c_compiler_stub",
    "c_compiler_stub"
   ],
   "host":[
    "python",
    "pip",
    "fmilib",
    "numpy",
    "cython",
    "python",
    "pip",
    "fmilib",
    "numpy",
    "cython",
    "python",
    "pip",
    "fmilib",
    "numpy",
    "cython"
   ],
   "run":[
    "python",
    "fmilib",
    "numpy",
    "scipy",
    "lxml",
    "assimulo >=3.0",
    "python",
    "fmilib",
    "numpy",
    "scipy",
    "lxml",
    "assimulo >=3.0",
    "python",
    "fmilib",
    "numpy",
    "scipy",
    "lxml",
    "assimulo >=3.0"
   ]
  },
  "source":{
   "fn":"PyFMI-2.6.tar.gz",
   "sha256":"c917575525c6b7e06a6e2c467dbbe547b370c8ba6bb76992a623e76333334c97",
   "url":"https://github.com/modelon-community/PyFMI/archive/PyFMI-2.6.tar.gz"
  },
  "test":{
   "imports":[
    "pyfmi",
    "pyfmi.common",
    "pyfmi.common.plotting",
    "pyfmi.examples",
    "pyfmi.simulation",
    "pyfmi",
    "pyfmi.common",
    "pyfmi.common.plotting",
    "pyfmi.examples",
    "pyfmi.simulation",
    "pyfmi",
    "pyfmi.common",
    "pyfmi.common.plotting",
    "pyfmi.examples",
    "pyfmi.simulation"
   ]
  }
 },
 "name":"pyfmi",
 "new_version":"2.7",
 "new_version_attempts":{
  "2.7":1
 },
 "new_version_errors":{},
 "pinning_version":"2020.03.06",
 "raw_meta_yaml":"{% set name = \"PyFMI\" %}\n{% set version = \"2.6\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.tar.gz\n  url: https://github.com/modelon-community/PyFMI/archive/PyFMI-{{ version }}.tar.gz\n  sha256: c917575525c6b7e06a6e2c467dbbe547b370c8ba6bb76992a623e76333334c97\n\nbuild:\n  number: 0\n\nrequirements:\n  build:\n    - {{ compiler('c') }}\n  host:\n    - python\n    - pip\n    - fmilib\n    - numpy\n    - cython\n  run:\n    - python\n    - fmilib\n    - {{ pin_compatible('numpy') }}\n    - scipy\n    - lxml\n    - assimulo >=3.0\n\ntest:\n  imports:\n    - pyfmi\n    - pyfmi.common\n    - pyfmi.common.plotting\n    - pyfmi.examples\n    - pyfmi.simulation\n\nabout:\n  home: http://www.jmodelica.org/\n  license: LGPL\n  license_file: LICENSE\n  summary: PyFMI is a package for loading and interacting with Functional Mock-Up Units\n\nextra:\n  recipe-maintainers:\n    - jschueller\n    - chria\n",
 "req":{
  "__set__":true,
  "elements":[
   "assimulo",
   "c_compiler_stub",
   "cython",
   "fmilib",
   "lxml",
   "numpy",
   "pip",
   "python",
   "scipy"
  ]
 },
 "requirements":{
  "build":{
   "__set__":true,
   "elements":[
    "c_compiler_stub"
   ]
  },
  "host":{
   "__set__":true,
   "elements":[
    "cython",
    "fmilib",
    "numpy",
    "pip",
    "python"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "assimulo",
    "fmilib",
    "lxml",
    "numpy",
    "python",
    "scipy"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "smithy_version":"3.6.9",
 "strong_exports":false,
 "total_requirements":{
  "build":{
   "__set__":true,
   "elements":[
    "c_compiler_stub"
   ]
  },
  "host":{
   "__set__":true,
   "elements":[
    "cython",
    "fmilib",
    "numpy",
    "pip",
    "python"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "assimulo >=3.0",
    "fmilib",
    "lxml",
    "numpy",
    "python",
    "scipy"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "url":"https://github.com/modelon/PyFMI/archive/PyFMI-2.5.4.tar.gz",
 "version":"2.6"
}