{
 "PRed":[
  {
   "PR":{
    "__lazy_json__":"pr_json/244791294.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"1.3.0"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad":{
  "exception":"[Errno 36] File name too long: '/opt/conda/envs/run_env/conda-bld/tmp66f1l53j/pytest-datadir-1.3.1/tests/test_hello/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt'",
  "traceback":[
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/utils.py\", line 830, in tar_xf",
   "    libarchive.extract_file(tarball, flags)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/libarchive/extract.py\", line 70, in extract_file",
   "    extract_entries(archive, flags)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/libarchive/extract.py\", line 50, in extract_entries",
   "    write_header(write_p, entry._entry_p)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/libarchive/ffi.py\", line 91, in check_int",
   "    raise archive_error(args[0], retcode)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/libarchive/ffi.py\", line 75, in archive_error",
   "    raise ArchiveError(msg, errno(archive_p), retcode, archive_p)",
   "libarchive.exception.ArchiveError: Could not stat pytest-datadir-1.3.1/tests/test_hello/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt (errno=36, retcode=-25, archive_p=94161133441280)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 682, in main",
   "    hash_type=attrs.get('hash_type', 'sha256'))",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.xsh\", line 98, in run",
   "    migrate_return = migrator.migrate(recipe_dir, attrs, **kwargs)",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators.xsh\", line 473, in migrate",
   "    return super().migrate(recipe_dir, attrs)",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators.xsh\", line 200, in migrate",
   "    mini_migrator.migrate(recipe_dir, attrs, **kwargs)",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators.xsh\", line 103, in migrate",
   "    cb_work_dir = provide(md)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 652, in provide",
   "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 148, in unpack",
   "    tar_xf(src_path, tmpdir)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/utils.py\", line 836, in tar_xf",
   "    _tar_xf_fallback(tarball, dir_path)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/utils.py\", line 784, in _tar_xf_fallback",
   "    t.extractall(path=dir_path)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/tarfile.py\", line 2002, in extractall",
   "    numeric_owner=numeric_owner)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/tarfile.py\", line 2044, in extract",
   "    numeric_owner=numeric_owner)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/tarfile.py\", line 2114, in _extract_member",
   "    self.makefile(tarinfo, targetpath)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/tarfile.py\", line 2155, in makefile",
   "    with bltn_open(targetpath, \"wb\") as target:",
   "OSError: [Errno 36] File name too long: '/opt/conda/envs/run_env/conda-bld/tmp66f1l53j/pytest-datadir-1.3.1/tests/test_hello/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt'",
   ""
  ]
 },
 "conda-forge.yml":{},
 "feedstock_name":"pytest-datadir",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "home":"https://github.com/gabrielcnr/pytest-datadir",
   "license":"MIT",
   "summary":"pytest plugin for manipulating test data directories and files."
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":"python -m pip install . --no-deps --ignore-installed"
  },
  "extra":{
   "recipe-maintainers":[
    "nicoddemus",
    "gabrielcnr",
    "edisongustavo",
    "gqmelo",
    "IgorTG",
    "nicoddemus",
    "gabrielcnr",
    "edisongustavo",
    "gqmelo",
    "IgorTG",
    "nicoddemus",
    "gabrielcnr",
    "edisongustavo",
    "gqmelo",
    "IgorTG"
   ]
  },
  "package":{
   "name":"pytest-datadir",
   "version":"1.3.0"
  },
  "requirements":{
   "build":[
    "pip",
    "setuptools_scm",
    "pip",
    "setuptools_scm",
    "pip",
    "setuptools_scm"
   ],
   "run":[
    "python",
    "pytest",
    "python",
    "pytest",
    "python",
    "pytest"
   ]
  },
  "source":{
   "fn":"pytest-datadir-1.3.0.tar.gz",
   "sha256":"275f641dbb045896c7d185cfbe79afd15270eed09d334c2ceb17396e634e22dd",
   "url":"https://pypi.io/packages/source/p/pytest-datadir/pytest-datadir-1.3.0.tar.gz"
  },
  "test":{
   "commands":[
    "pytest --help",
    "pytest --help",
    "pytest --help"
   ],
   "imports":[
    "pytest_datadir",
    "pytest_datadir",
    "pytest_datadir"
   ],
   "requires":[
    "pytest",
    "pytest",
    "pytest"
   ]
  }
 },
 "name":"pytest-datadir",
 "new_version":"1.3.1",
 "pinning_version":"2019.01.09",
 "raw_meta_yaml":"{% set name = \"pytest-datadir\" %}\n{% set version = \"1.3.0\" %}\n{% set sha256 = \"275f641dbb045896c7d185cfbe79afd15270eed09d334c2ceb17396e634e22dd\" %}\n{% set ext = \"tar.gz\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  fn: {{ name }}-{{ version }}.{{ ext }}\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}\n  sha256: {{ sha256 }}\n\nbuild:\n  number: 0\n  noarch: python\n  script: python -m pip install . --no-deps --ignore-installed\n\nrequirements:\n  build:\n    - pip\n    - setuptools_scm\n  run:\n    - python\n    - pytest\n\ntest:\n  requires:\n    - pytest\n  imports:\n    - pytest_datadir\n  commands:\n    - pytest --help\n\nabout:\n  home: https://github.com/gabrielcnr/pytest-datadir\n  license: MIT\n  summary: pytest plugin for manipulating test data directories and files.\n\nextra:\n  recipe-maintainers:\n    - nicoddemus\n    - gabrielcnr\n    - edisongustavo\n    - gqmelo\n    - IgorTG\n",
 "req":{
  "__set__":true,
  "elements":[
   "pip",
   "pytest",
   "python",
   "setuptools_scm"
  ]
 },
 "smithy_version":"3.2.2",
 "url":"https://pypi.io/packages/source/p/pytest-datadir/pytest-datadir-1.3.0.tar.gz",
 "version":"1.3.0"
}