{
 "PRed":[
  {
   "PR":{
    "__lazy_json__":"pr_json/221637194.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"CompilerRebuild",
    "migrator_version":1,
    "name":"Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/224511606.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"0.9.8"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/235293205.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"0.9.9"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/286918214.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"1.0.0"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR":{
    "__lazy_json__":"pr_json/336019799.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"MigrationYaml",
    "migrator_object_version":1,
    "migrator_version":0,
    "name":"python38"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad":{
  "exception":"Failed to put item: An error occurred (ValidationException) on request (14ERKLMQQ2U04T6K4SUN26PS27VV4KQNSO5AEMVJF66Q9ASUAAJG) on table (pr_json) when calling the PutItem operation: Attempting to store more than 38 significant digits in a Number",
  "traceback":[
   "Traceback (most recent call last):",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 849, in main",
   "    hash_type=attrs.get(\"hash_type\", \"sha256\"),",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 248, in run",
   "    PRJson.dump(pr_json)",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/dynamo_models.py\", line 33, in dump",
   "    item.save()",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/pynamodb/models.py\", line 405, in save",
   "    data = self._get_connection().put_item(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/pynamodb/connection/table.py\", line 139, in put_item",
   "    return_item_collection_metrics=return_item_collection_metrics)",
   "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/pynamodb/connection/base.py\", line 972, in put_item",
   "    six.raise_from(PutError(\"Failed to put item: {}\".format(e), e), None)",
   "  File \"<string>\", line 3, in raise_from",
   "pynamodb.exceptions.PutError: Failed to put item: An error occurred (ValidationException) on request (14ERKLMQQ2U04T6K4SUN26PS27VV4KQNSO5AEMVJF66Q9ASUAAJG) on table (pr_json) when calling the PutItem operation: Attempting to store more than 38 significant digits in a Number",
   ""
  ]
 },
 "conda-forge.yml":{
  "compiler_stack":"comp7",
  "max_py_ver":"37",
  "max_r_ver":"35",
  "provider":{
   "win":"azure"
  }
 },
 "feedstock_name":"requests-futures",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "home":"https://github.com/ross/requests-futures",
   "license":"Apache 2.0",
   "license_file":"LICENSE",
   "summary":"Asynchronous Python HTTP for Humans"
  },
  "build":{
   "number":"0",
   "script":" -m pip install . --no-deps --ignore-installed -vvv"
  },
  "extra":{
   "recipe-maintainers":[
    "pmlandwehr",
    "ocefpaf",
    "pmlandwehr",
    "ocefpaf",
    "pmlandwehr",
    "ocefpaf"
   ]
  },
  "package":{
   "name":"requests-futures",
   "version":"1.0.0"
  },
  "requirements":{
   "host":[
    "python",
    "pip",
    "python",
    "pip",
    "python",
    "pip"
   ],
   "run":[
    "python",
    "requests >=1.2.0",
    "python",
    "requests >=1.2.0",
    "python",
    "requests >=1.2.0"
   ]
  },
  "source":{
   "sha256":"35547502bf1958044716a03a2f47092a89efe8f9789ab0c4c528d9c9c30bc148",
   "url":"https://pypi.io/packages/source/r/requests-futures/requests-futures-1.0.0.tar.gz"
  },
  "test":{
   "imports":[
    "requests_futures",
    "requests_futures",
    "requests_futures"
   ]
  }
 },
 "name":"requests-futures",
 "new_version":"1.0.0",
 "pinning_version":"2019.11.01",
 "raw_meta_yaml":"{% set version = \"1.0.0\" %}\n\npackage:\n  name: requests-futures\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/r/requests-futures/requests-futures-{{ version }}.tar.gz\n  sha256: 35547502bf1958044716a03a2f47092a89efe8f9789ab0c4c528d9c9c30bc148\n\nbuild:\n  number: 0\n  script: \"{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv\"\n\nrequirements:\n  host:\n    - python\n    - pip\n  run:\n    - python\n    - requests >=1.2.0\n    - futures >=2.1.3  # [py<32]\n\ntest:\n  imports:\n    - requests_futures\n\nabout:\n  home: https://github.com/ross/requests-futures\n  license: Apache 2.0\n  license_file: LICENSE\n  summary: 'Asynchronous Python HTTP for Humans'\n\nextra:\n  recipe-maintainers:\n    - pmlandwehr\n    - ocefpaf\n",
 "req":{
  "__set__":true,
  "elements":[
   "pip",
   "python",
   "requests"
  ]
 },
 "requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python",
    "requests"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "smithy_version":"3.6.1",
 "strong_exports":false,
 "total_requirements":{
  "build":{
   "__set__":true,
   "elements":[]
  },
  "host":{
   "__set__":true,
   "elements":[
    "pip",
    "python"
   ]
  },
  "run":{
   "__set__":true,
   "elements":[
    "python",
    "requests >=1.2.0"
   ]
  },
  "test":{
   "__set__":true,
   "elements":[]
  }
 },
 "url":"https://pypi.io/packages/source/r/requests-futures/requests-futures-1.0.0.tar.gz",
 "version":"1.0.0"
}