{
 "exception":"Command '['git', 'clone', '-q', 'https://github.com/conda-forge/google-api-core-split-feedstock.git', './feedstocks/google-api-core-feedstock']' returned non-zero exit status 128.",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 265, in main",
  "    deps = v[\"run\"](fctx, ctx, import_map)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 53, in depfinder_audit_feedstock",
  "    feedstock_dir=feedstock_dir, origin=origin, upstream=origin, branch=\"master\",",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/git_xonsh_utils.xsh\", line 10, in fetch_repo",
  "    p = ![git clone -q @(origin) @(feedstock_dir)]",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 22847, in subproc_captured_hiddenobject",
  "    return run_subproc(cmds, captured=\"hiddenobject\")",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 22806, in run_subproc",
  "    command.end()",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15653, in end",
  "    self._end(tee_output=tee_output)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15672, in _end",
  "    self._raise_subproc_error()",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15798, in _raise_subproc_error",
  "    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)",
  "subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'https://github.com/conda-forge/google-api-core-split-feedstock.git', './feedstocks/google-api-core-feedstock']' returned non-zero exit status 128.",
  ""
 ]
}