{
 "exception":"Command '['/opt/conda/envs/run_env/bin/git', 'checkout', '1.0']' returned non-zero exit status 1.",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 117, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 32, in depfinder_audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 68, in _get_source_code",
  "    return provide(md)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 657, in provide",
  "    verbose=metadata.config.verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 330, in git_source",
  "    git_depth=git_depth, is_top_level=True, verbose=verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 261, in git_mirror_checkout_recursive",
  "    cwd=checkout_dir, stdout=stdout, stderr=stderr)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/utils.py\", line 404, in check_call_env",
  "    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/utils.py\", line 395, in _func_defaulting_env_to_os_environ",
  "    subprocess.check_call(_args, **kwargs)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/subprocess.py\", line 363, in check_call",
  "    raise CalledProcessError(retcode, cmd)",
  "subprocess.CalledProcessError: Command '['/opt/conda/envs/run_env/bin/git', 'checkout', '1.0']' returned non-zero exit status 1.",
  ""
 ]
}