{
 "exception":"Received dictionary as spec.  Note that pip requirements are not supported in conda-build meta.yaml.  Error message: Invalid version '-7.1.1': empty version component",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 38, in __call__",
  "    return cls._cache_[arg]",
  "KeyError: '>=5,!=7.1.0,!=-7.1.1'",
  "",
  "During handling of the above exception, another exception occurred:",
  "",
  "Traceback (most recent call last):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 38, in __call__",
  "    return cls._cache_[arg]",
  "KeyError: '!=-7.1.1'",
  "",
  "During handling of the above exception, another exception occurred:",
  "",
  "Traceback (most recent call last):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 38, in __call__",
  "    return cls._cache_[arg]",
  "KeyError: '-7.1.1'",
  "",
  "During handling of the above exception, another exception occurred:",
  "",
  "Traceback (most recent call last):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 1195, in ms_depends",
  "    ms = MatchSpec(spec)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/match_spec.py\", line 54, in __call__",
  "    return super(MatchSpecType, cls).__call__(**parsed)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/match_spec.py\", line 176, in __init__",
  "    self._match_components = self._build_components(**kwargs)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/match_spec.py\", line 398, in _build_components",
  "    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/match_spec.py\", line 398, in <genexpr>",
  "    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/match_spec.py\", line 412, in _make_component",
  "    matcher = _implementors[field_name](value)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 40, in __call__",
  "    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 488, in __init__",
  "    vspec_str, matcher, is_exact = self.get_matcher(vspec)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 499, in get_matcher",
  "    tup = tuple(VersionSpec(s) for s in vspec_tree[1:])",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 499, in <genexpr>",
  "    tup = tuple(VersionSpec(s) for s in vspec_tree[1:])",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 40, in __call__",
  "    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 488, in __init__",
  "    vspec_str, matcher, is_exact = self.get_matcher(vspec)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 537, in get_matcher",
  "    self.matcher_vo = VersionOrder(vo_str)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 40, in __call__",
  "    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/models/version.py\", line 211, in __init__",
  "    raise InvalidVersionSpec(vstr, \"empty version component\")",
  "conda.exceptions.InvalidVersionSpec: Invalid version '-7.1.1': empty version component",
  "",
  "During handling of the above exception, another exception occurred:",
  "",
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 108, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 32, in depfinder_audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 62, in _get_source_code",
  "    recipe_dir, config=Config(**CB_CONFIG), finalize=False, bypass_env_check=True,",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/api.py\", line 45, in render",
  "    permit_unsatisfiable_variants=permit_unsatisfiable_variants)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 830, in render_recipe",
  "    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 745, in distribute_variants",
  "    (mv, need_source_download, None)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 1323, in dist",
  "    return '%s-%s-%s' % (self.name(), self.version(), self.build_id())",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 1306, in build_id",
  "    out = build_string_from_metadata(self)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 563, in build_string_from_metadata",
  "    for ms in metadata.ms_depends('run'):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 1200, in ms_depends",
  "    \"not supported in conda-build meta.yaml.  Error message: \" + str(e))",
  "RuntimeError: Received dictionary as spec.  Note that pip requirements are not supported in conda-build meta.yaml.  Error message: Invalid version '-7.1.1': empty version component",
  ""
 ]
}