{
 "exception":"SHA256 mismatch: '141c3dc57ed6c897e7e81cd9f79c020ce1f80de015bb2de4a078e1990adf6c7b' != 'bba7cf5e24a0bd774dac2783c1394acd9503c594833304aa518e78e845f72c8b'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 385, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 77, in depfinder_audit_feedstock",
  "    return extract_deps_from_source(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 59, in extract_deps_from_source",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 890, in _get_source_code",
  "    return provide(md)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 724, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 141, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 107, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: '141c3dc57ed6c897e7e81cd9f79c020ce1f80de015bb2de4a078e1990adf6c7b' != 'bba7cf5e24a0bd774dac2783c1394acd9503c594833304aa518e78e845f72c8b'",
  ""
 ]
}