{
 "exception": "SHA256 mismatch: '85715775010894888ee972d58bb92bbd2e1f58fd340efe94d604d2933758cb1e' != '6f1365702a0fde18837143f1a5777795c4cd89b3cbf8b05a5a8cdc26a04180e8'",
 "traceback": [
  "Traceback (most recent call last):",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 393, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 79, in depfinder_audit_feedstock",
  "    return extract_deps_from_source(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py\", line 59, in extract_deps_from_source",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 902, in _get_source_code",
  "    return provide(md)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 724, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 141, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 107, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: '85715775010894888ee972d58bb92bbd2e1f58fd340efe94d604d2933758cb1e' != '6f1365702a0fde18837143f1a5777795c4cd89b3cbf8b05a5a8cdc26a04180e8'",
  ""
 ]
}