exception: list index out of range
traceback: ['Traceback (most recent call last):', '  File "/root/repo/cf-scripts/conda_forge_tick/audit.py",
    line 232, in main', '    deps = v["run"](fctx, ctx)', '  File "/root/repo/cf-scripts/conda_forge_tick/audit.py",
    line 50, in grayskull_audit_feedstock', '    "pypi", pkg_name, pkg_version, download=False,',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/factory.py",
    line 23, in create_recipe', '    name, version, **kwargs', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 58, in __init__', '    super(PyPi, self).__init__(name=name, version=str(version)
    if version else None)', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/base_recipe.py",
    line 58, in __init__', '    self.update_all_recipe()', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/base_recipe.py",
    line 112, in update_all_recipe', '    self.refresh_section(section)', '  File
    "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 522, in refresh_section', '    metadata = self._get_metadata()', '  File
    "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 565, in _get_metadata', '    all_requirements["host"], self.PYPI_CONFIG',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/track_packages.py",
    line 38, in solve_list_pkg_name', '    return [re_norm.sub(",", solve_pkg_name(pkg,
    config_file)) for pkg in list_pkg]', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/track_packages.py",
    line 38, in <listcomp>', '    return [re_norm.sub(",", solve_pkg_name(pkg, config_file))
    for pkg in list_pkg]', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/track_packages.py",
    line 43, in solve_pkg_name', '    config_pkg = track_package(pkg_name_sep[0],
    config_file)', 'IndexError: list index out of range', '']
