{
 "exception":"Command '['git', 'fetch', 'https://github.com/conda-forge/airflow-split-feedstock.git', '--quiet']' returned non-zero exit status 128.",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 68, in main",
  "    deps = audit_feedstock(fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 25, in audit_feedstock",
  "    feedstock_dir=feedstock_dir, origin=origin, upstream=origin, branch=\"master\"",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/git_xonsh_utils.xsh\", line 17, in fetch_repo",
  "    git fetch @(origin) --quiet",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 22645, in subproc_captured_hiddenobject",
  "    return run_subproc(cmds, captured=\"hiddenobject\")",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 22604, in run_subproc",
  "    command.end()",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15735, in end",
  "    self._end(tee_output=tee_output)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15754, in _end",
  "    self._raise_subproc_error()",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/xonsh/__amalgam__.py\", line 15880, in _raise_subproc_error",
  "    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)",
  "subprocess.CalledProcessError: Command '['git', 'fetch', 'https://github.com/conda-forge/airflow-split-feedstock.git', '--quiet']' returned non-zero exit status 128.",
  ""
 ]
}