{
 "exception":"SHA256 mismatch: 'dc972ce8ab5c1f4aa93f5f1f24ee962e7bed25c6d46c86389ec7ff923f3fdab4' != '1e7b3b0a6e4b75866c43143a357ae3049a6a9942c934b0c54dd622153ee02411'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 67, in main",
  "    deps = audit_feedstock(fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 30, in audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 73, in _get_source_code",
  "    return provide(md)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 654, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 139, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 105, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: 'dc972ce8ab5c1f4aa93f5f1f24ee962e7bed25c6d46c86389ec7ff923f3fdab4' != '1e7b3b0a6e4b75866c43143a357ae3049a6a9942c934b0c54dd622153ee02411'",
  ""
 ]
}